identifier: bosch_application_board_3_0
name: Bosch Application Board 3.0
type: mcu
arch: arm
ram: 256
flash: 1024
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - ble
  - counter
  - gpio
  - i2c
  - spi
  - usb_cdc
  - usb_device
  - watchdog
  - netif:openthread
vendor: bosch
